# SageMaker PyTorch image
FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-training:1.10.2-transformers4.17.0-gpu-py38-cu113-ubuntu20.04

RUN pip3 install sagemaker-training
RUN pip3 install datasets -U
RUN pip3 install pynvml

